<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenCombatEngine.Core\OpenCombatEngine.Core.csproj" />
    <ProjectReference Include="..\OpenCombatEngine.Implementation\OpenCombatEngine.Implementation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\system_engine.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
